### ISSUE TITLE
Remove nav bar, search instructions, and heading from printed housing results

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#23]
The navigation bar, footer, instructions about how to do a housing search, and "Affordable Housing Database" are all still shown in the printed version of the housing search results but can be omitted.

**Comment by clairehubel** [comment]
I think removing these on the printed version would be good. The less visual clutter the better.

**Comment by philhawksworth** [comment]
I'd make a case for keeping the primary navigation visible on the printed view, as it gives anyone looking at that print out who might later return to the site to do another search, some guidance on where to find that page again (we indicate the active section of the site in the navigation).

A fix is in to:
- reduce the size of the logo and the navigation in the print view
- remove the footer and pre-footer
- remove any buttons which cannot be clicked and add no direction finding
- remove the map links from the results (since we display external link URLs in prints, but these are too long to type )
- adds a `noprint` utility class to the CSS which can be added to any HTML element to hide it in prints

See it here: https://feat-result-print-view--ueo.netlify.app/housing/affordable-housing/

**Comment by trevorshannon** [comment]
amazing!  looks good to me; curious what @clairehubel thinks.

I am not too familiar with print layouts. Is there a way to force page breaks to be between `<li>` items?  Just to prevent this kind of thing:

<img width="553" alt="Screen Shot 2022-05-13 at 11 04 08 AM" src="https://user-images.githubusercontent.com/4656936/168341920-2a591d34-429a-484f-92d3-7ec7f584e506.png">

**Comment by philhawksworth** [comment]
ah! There is indeed. Good spot. Added that fix.
