### ISSUE TITLE
Add property contact email to Airtable database

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#31]
There is a phone number field for each rental property, but no contact email.  There is a contact email for at least some of the properties in the current housing db.

Assigning to @philhawksworth as he wrote the scraper to pull data into the Airtable in the first place.

**Comment by clairehubel** [comment]
It would be great to include this, since calling the property is often a dead end, as we discussed.

**Comment by trevorshannon** [comment]
@philhawksworth I am not seeing a contact email in the new data import.  Are you able to add that in, or at least generate a mapping of some kind, e.g. apartment name --> contact email?

I was able to download the latest MSSQL backup file that Poul generated the other day, but can't figure out how to do anything with it in order to extract the email address data.

**Comment by philhawksworth** [comment]
Yeah sadly the DB backup is not quite the format we need to be able to easily wrangle content unless we have the same DB software. I'd hoped we could get an _export_ rather than a _backup_, that way we could have had data in a portable non-proprietary format

No matter! I've re-scraped, parsed and imported the content to include a contact email in the `[Import] Housing Database` table.

As such, I'm closing this issue as the effort on this is done assuming that #20 gets completed.

**Comment by philhawksworth** [comment]
An JSON export is very doable directly from MS SQL, which is what this appears to be. But I think access to the machine housing the DB is somewhat limited.

Regardless,  I don't think we need to put effort into exporting any more data from what will be the legacy DB once we have ceased making updates to it. (Which should already be a threshold we have crossed. 

The only consumer of this data is now the new website, from Airtable. And it is already beginning to evolve beyond the legacy DB schema and content.

**Comment by trevorshannon** [comment]
Even so, having a readable format of the legacy data would be good to have just in case.  There could be data stored there that is not rendered on the old website or we may have to check the old data for some reason.  I'll look into how to create this readable format but it'll be low priority for sure.
