### ISSUE TITLE
Sort rent tables by rent amount

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#66]

**Comment by trevorshannon** [comment]
example:
https://ueo.netlify.app/housing/affordable-housing/901

**Comment by clairehubel** [comment]
I would love to see a minor tweak of the formatting of the info that appears under the hover arrows, if possible. Would it be possible to remove the  (1), (2), (3) etc....? I think these are extraneous.

Additionally, if the formatting could be aligned so that there is one row for each household size, I think it would be clearer visually. Is that possible? I know it's nitpicky, but I think it would make the info clearer to absorb.

**Comment by trevorshannon** [comment]
not nitpicky at all!  I agree with that the formatting of the max rent info should be improved, and that's something that will be done as soon as the final data import from SQL is finished.  There is already an issue for this in #45.

As for the rent table rows, I'm still trying to figure out the best way to show this. For each unit type there may be multiple income brackets, and for each income bracket there may be multiple household sizes.  It quickly becomes a large number of table rows.  Issue #49 exists along these lines already and #32 is related as well.

I'll keep this issue to be only about sorting the resulting table appropriately (whatever that table may end up looking like)

**Comment by trevorshannon** [comment]
fixed in #82
