### ISSUE TITLE
Move content of 'Housing' into 'Resources'

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#69]
per discussion with @clairehubel and weiqune tonight.

Includes moving the affordable housing database search page into the main menu in the header

**Comment by clairehubel** [comment]
@philhawksworth let's chat about the best way to make this clearer as well. I'm thinking some compromise may be needed to preserve the simplicity and maintain the intuitiveness of the structure. You're good at thinking through structure and clarity.

**Comment by trevorshannon** [comment]
I have an example of one way to organize it.  I'll make a link shortly.

**Comment by clairehubel** [comment]
This does accomplish some of what Wei was requesting, but to me it is confusing, and I'd rather see housing resources grouped together, especially since coming down the road we are hoping to add all the other resources to the resource section. Perhaps the general resource directory that we are planning can just have housing as one of the tags that people can search? I'm wondering if there is another way to accommodate her request.....I don't have skills to sketch it out, but can try to chat to @philhawksworth about it tomorrow. I think one of his strengths is helping to design a clear structure. 

Thanks for taking a stab at this Trevor. Maybe we can even make several mock-up versions to see which one she likes best?

**Comment by philhawksworth** [comment]
Reshuffle done!

**Comment by trevorshannon** [comment]
weiqune is requesting that the housing resources be moved into Resources.  reopening.
