### ISSUE TITLE
Move California LifeLine Phone Program out of "Cash Assistance" heading

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#71]
The LifeLine program is not really a cash assistance program.

per discussion with @clairehubel and weiqune, it could be in it's own heading with a title such as "Technology Assistance"

Either in the heading or in the link to the program itself, the fact that it's a free phone with free service (no monthly bill) should be emphasized.

**Comment by philhawksworth** [comment]
Absolutely. I think this provokes a slightly wider discussion about what "Cash Assistance" means. Because this scheme helps subsidise something, in the same way as the subsidy for assistive dogs scheme ([ASDA](https://ueo.netlify.app/public-assistance/assistance-dog-special-allowance/)) which is listed in the same section.

We can juggle and categorise these very easily together when we chat

**Comment by philhawksworth** [comment]
New heading added and item moved.
