### ISSUE TITLE
Fix phone link for shelter referrals

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#73]
The link itself seems fine (though adding +1 to the beginning is not a bad idea) but weiqune thought the link was broken, so perhaps just change the hyperlinked text to be the phone number itself.

https://ueo.netlify.app/resources/

**Comment by philhawksworth** [comment]
I'd strongly advocate for keeping phone numbers clickable to make it as easy as possible for users to take action when they find the phone number they need. 

Perhaps we can make it more obvious that these links are phone numbers with a bit of styling that prepends a phone icon to any link which is a phone number. 

(A bit of CSS and SVG to the rescue!)

**Comment by trevorshannon** [comment]
Yes, agree it should be a link.  I think to make it more clear _only_ the phone number should be a link and not the surrounding text.  One idea I had was to use the `Description` field to put in the non-hyperlinked words and make the `Title` just the phone number itself.  

or support markdown in the `Title`

**Comment by philhawksworth** [comment]
Adding richer markdown support is a little fiddly while we are using Airtable as the content authoring tool. But you're absolutely right that the convention we should use is that on the phone number is a link and not the text around it.

As you mention, we might need to rethink how we manage that content in that section of the site since it is currently just a list of links with no richer content management ability. We can solve it, but perhaps it would be good for us to chat about so that we land on the best way for the content to be managed in that table.

**Comment by philhawksworth** [comment]
If markdown is present in the Markdown field on the Resources Database table that is rendered. Otherwise the previous URL and Title combo are used.
