### ISSUE TITLE
Revisit telephone icon before phone numbers

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#80]
@philhawksworth  A while back, I experimented with a phone icon and I used the exact same HTML symbol that's in there now.  

Unfortunately, the rendering on my android phone is less than ideal.  The icons are red, and having a "warning" color like that on each result was a bit too much for me.  Maybe there is a different way to do it or (as my ux designer friend mentioned) doing without the icon is perhaps even better visually.

![Screenshot_20220514-143824](https://user-images.githubusercontent.com/4656936/168448971-160f18e3-5605-4222-b6c9-27c371bf05d1.png)

**Comment by philhawksworth** [comment]
Aha, thanks for this test. I used the unicode character which lets each each device render it with its own style. An SVG will be better. I'll do that.

**Comment by trevorshannon** [comment]
I wonder if the icon is necessary at all.  I think most people will recognize the formatting as a phone number anyways.

**Comment by philhawksworth** [comment]
I agree with you @trevorshannon. the main motivation for adding this icon was to avoid misunderstanding about a specific link, which included text as well as the number, should do. that link has been revised so that we only set the phone muber itself as the text in a link, so I think we have resolved the issue without needing to complicate the UI with this additional signposting.

Icon removed.
